services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DATABASE_URL=postgres://postgres:123456@db:5432/dbname
    command: sh -c "npm run build && npm start"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    networks:
      - app_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app_network:
